<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>CameraAutoUpload.Windows</AssemblyName>
    <RootNamespace>CameraAutoUpload.Windows</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.0.4</Version>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.IO" />
    <Using Include="System.Linq" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
    <Using Include="System.Net.Http" />
  </ItemGroup>
</Project>
