package com.nikonautoupload;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;

import java.util.*;

/** UI for the separate sports-card / photo-overlay module. */
public class OverlayStudioActivity extends Activity {
    private static final int REQ_LOGO=301,REQ_PREVIEW=302;
    private final int bg=Color.rgb(7,11,15),panel=Color.rgb(16,23,31),line=Color.rgb(42,54,66),white=Color.rgb(245,247,250),muted=Color.rgb(155,166,178),blue=Color.rgb(33,150,243),green=Color.rgb(55,206,108),amber=Color.rgb(255,193,7),red=Color.rgb(239,83,80);
    private SharedPreferences p;
    private LinearLayout body;
    private OverlayProcessor.Template editingTemplate;
    private EditorView editorView;
    private Uri previewSource;
    private ImageView previewImage;

    @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("settings",MODE_PRIVATE);OverlayProcessor.loadTemplates(this);drawMain();}

    private void base(String title){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setPadding(dp(14),dp(8),dp(14),dp(10));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹",Color.rgb(55,65,76));back.setTextSize(26);back.setOnClickListener(v->{if(editingTemplate!=null){editingTemplate=null;drawMain();}else finish();});top.addView(back,new LinearLayout.LayoutParams(dp(54),dp(52)));TextView t=text(title,22,white,true);top.addView(t,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(top);
        ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
        if(Build.VERSION.SDK_INT>=20){root.setOnApplyWindowInsetsListener((v,insets)->{root.setPadding(dp(14),dp(8),dp(14),Math.max(dp(10),insets.getSystemWindowInsetBottom()+dp(4)));return insets;});root.requestApplyInsets();}
    }

    private void drawMain(){editingTemplate=null;base("Photo Overlays / Sports Cards");
        LinearLayout info=card();info.addView(text("SEPARATE PHOTO-PROCESSING MODULE",13,blue,true));info.addView(text("Camera originals are never edited. When enabled, the app creates a second card/overlay copy after import. USB-C, FTP, Wi-Fi, Bluetooth and camera memory-card files stay untouched.",13,muted,false));body.addView(info);

        section("Shoot setup");LinearLayout setup=card();
        setup.addView(statusRow("Camera",cameraName(),green));setup.addView(statusRow("Import",ConnectionStatus.cameraConnection(p),blue));
        EditText team=input("Team name",p.getString("overlay_team",""));setup.addView(team);EditText event=input("Event / game",p.getString("overlay_event",""));setup.addView(event);EditText player=input("Player name",p.getString("overlay_player",""));setup.addView(player);EditText number=input("Player number",p.getString("overlay_number",""));setup.addView(number);EditText photographer=input("Photographer / logo text",p.getString("overlay_photographer",""));setup.addView(photographer);

        ArrayList<OverlayProcessor.Template> templates=OverlayProcessor.loadTemplates(this);ArrayList<OverlayProcessor.Template> portraits=new ArrayList<>(),landscapes=new ArrayList<>();for(OverlayProcessor.Template x:templates){if("portrait".equals(x.orientation))portraits.add(x);else landscapes.add(x);}
        setup.addView(text("Portrait template",12,muted,true));Spinner portrait=templateSpinner(portraits,p.getString(OverlayProcessor.PREF_PORTRAIT_TEMPLATE,""));setup.addView(portrait,new LinearLayout.LayoutParams(-1,dp(52)));
        setup.addView(text("Landscape template",12,muted,true));Spinner landscape=templateSpinner(landscapes,p.getString(OverlayProcessor.PREF_LANDSCAPE_TEMPLATE,""));setup.addView(landscape,new LinearLayout.LayoutParams(-1,dp(52)));
        setup.addView(text("Flickr upload",12,muted,true));Spinner upload=new Spinner(this);String[] uploadLabels={"Original only","Overlay / Card version only","Both"};upload.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,uploadLabels));String choice=p.getString(OverlayProcessor.PREF_UPLOAD_CHOICE,OverlayProcessor.CHOICE_ORIGINAL);upload.setSelection(OverlayProcessor.CHOICE_OVERLAY.equals(choice)?1:(OverlayProcessor.CHOICE_BOTH.equals(choice)?2:0));setup.addView(upload,new LinearLayout.LayoutParams(-1,dp(52)));
        Switch auto=new Switch(this);styleSwitch(auto,"Automatic overlay processing",p.getBoolean(OverlayProcessor.PREF_AUTO,false));setup.addView(auto);
        Switch hold=new Switch(this);styleSwitch(hold,"Hold finished card for preview before Flickr upload",p.getBoolean(OverlayProcessor.PREF_HOLD_PREVIEW,false));setup.addView(hold);
        Button save=button("SAVE SHOOT SETUP",green);save.setOnClickListener(v->{
            SharedPreferences.Editor e=p.edit().putString("overlay_team",team.getText().toString().trim()).putString("overlay_event",event.getText().toString().trim()).putString("overlay_player",player.getText().toString().trim()).putString("overlay_number",number.getText().toString().trim()).putString("overlay_photographer",photographer.getText().toString().trim()).putBoolean(OverlayProcessor.PREF_AUTO,auto.isChecked()).putBoolean(OverlayProcessor.PREF_HOLD_PREVIEW,hold.isChecked());
            OverlayProcessor.Template pt=selectedTemplate(portraits,portrait),lt=selectedTemplate(landscapes,landscape);if(pt!=null)e.putString(OverlayProcessor.PREF_PORTRAIT_TEMPLATE,pt.id);if(lt!=null)e.putString(OverlayProcessor.PREF_LANDSCAPE_TEMPLATE,lt.id);String q=upload.getSelectedItemPosition()==1?OverlayProcessor.CHOICE_OVERLAY:(upload.getSelectedItemPosition()==2?OverlayProcessor.CHOICE_BOTH:OverlayProcessor.CHOICE_ORIGINAL);e.putString(OverlayProcessor.PREF_UPLOAD_CHOICE,q).apply();toast("Shoot setup saved");drawMain();});setup.addView(save);body.addView(setup);

        section("Preview");LinearLayout preview=card();previewImage=new ImageView(this);previewImage.setScaleType(ImageView.ScaleType.FIT_CENTER);previewImage.setBackgroundColor(Color.rgb(9,14,19));preview.addView(previewImage,new LinearLayout.LayoutParams(-1,dp(220)));TextView ps=text("Choose a phone photo to preview the currently selected portrait/landscape card.",12,muted,false);preview.addView(ps);Button choose=button("CHOOSE PHOTO FOR PREVIEW",blue);choose.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_PREVIEW);});preview.addView(choose);
        String last=p.getString("overlay_last_uri","");if(!last.isEmpty()){Button lastPreview=button("SHOW LAST FINISHED CARD",Color.rgb(70,80,90));lastPreview.setOnClickListener(v->{try{previewImage.setImageURI(Uri.parse(last));}catch(Exception e){toast("Could not open last card");}});preview.addView(lastPreview);}
        Set<String> pending=p.getStringSet("overlay_preview_pending_uris",Collections.emptySet());if(!last.isEmpty()&&pending.contains(last)){LinearLayout a=new LinearLayout(this);Button approve=button("APPROVE FOR FLICKR",green);approve.setOnClickListener(v->{OverlayProcessor.approvePreview(this,Uri.parse(last));toast("Card approved and queued");drawMain();});a.addView(approve,new LinearLayout.LayoutParams(0,dp(52),1));Button phone=button("KEEP PHONE ONLY",amber);phone.setOnClickListener(v->{OverlayProcessor.rejectPreview(this,Uri.parse(last));toast("Card kept on phone only");drawMain();});a.addView(phone,new LinearLayout.LayoutParams(0,dp(52),1));preview.addView(a);}body.addView(preview);

        section("Reusable templates");Button add=button("+ NEW CUSTOM TEMPLATE",green);add.setOnClickListener(v->{OverlayProcessor.Template t=new OverlayProcessor.Template();t.name="Custom Template";t.category="Custom";t.orientation="landscape";drawEditor(t);});body.addView(add);
        for(OverlayProcessor.Template t:templates){LinearLayout row=card();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=text(t.name+"\n"+t.category+" • "+t.orientation,14,white,true);top.addView(title,new LinearLayout.LayoutParams(0,dp(58),1));Button use=button("USE",blue);use.setOnClickListener(v->{p.edit().putString("portrait".equals(t.orientation)?OverlayProcessor.PREF_PORTRAIT_TEMPLATE:OverlayProcessor.PREF_LANDSCAPE_TEMPLATE,t.id).apply();toast(t.name+" selected");drawMain();});top.addView(use,new LinearLayout.LayoutParams(dp(76),dp(50)));Button edit=button("EDIT",Color.rgb(70,80,90));edit.setOnClickListener(v->drawEditor(t));top.addView(edit,new LinearLayout.LayoutParams(dp(76),dp(50)));row.addView(top);body.addView(row);}
    }

    private String cameraName(){String n=p.getString("usb_camera_name","");if(!n.isEmpty())return n;try{return MultiCameraSupport.cameraName(p);}catch(Exception e){return "Camera";}}

    private Spinner templateSpinner(ArrayList<OverlayProcessor.Template> list,String selected){Spinner s=new Spinner(this);ArrayList<String> names=new ArrayList<>();for(OverlayProcessor.Template t:list)names.add(t.name);if(names.isEmpty())names.add("No template available");s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));for(int i=0;i<list.size();i++)if(list.get(i).id.equals(selected)){s.setSelection(i);break;}return s;}
    private OverlayProcessor.Template selectedTemplate(ArrayList<OverlayProcessor.Template> list,Spinner s){int i=s.getSelectedItemPosition();return i>=0&&i<list.size()?list.get(i):null;}

    private void drawEditor(OverlayProcessor.Template source){editingTemplate=source;base("Template Editor");
        LinearLayout info=card();info.addView(text("Drag an element to move it. Use two fingers on the selected element to pinch-resize and twist-rotate. Logos/graphics can be transparent PNG files.",12,muted,false));body.addView(info);
        EditText name=input("Template name",editingTemplate.name);body.addView(name);Spinner orient=new Spinner(this);orient.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"landscape","portrait"}));orient.setSelection("portrait".equals(editingTemplate.orientation)?1:0);body.addView(orient,new LinearLayout.LayoutParams(-1,dp(50)));
        editorView=new EditorView(this,editingTemplate);body.addView(editorView,new LinearLayout.LayoutParams(-1,dp(420)));

        LinearLayout add=new LinearLayout(this);Button addText=button("+ TEXT",blue);addText.setOnClickListener(v->addText());add.addView(addText,new LinearLayout.LayoutParams(0,dp(52),1));Button addLogo=button("+ LOGO / PNG",green);addLogo.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_LOGO);});add.addView(addLogo,new LinearLayout.LayoutParams(0,dp(52),1));Button addRect=button("+ GRAPHIC",Color.rgb(70,80,90));addRect.setOnClickListener(v->{OverlayProcessor.Element e=new OverlayProcessor.Element();e.type="rect";e.x=.15f;e.y=.15f;e.w=.7f;e.h=.7f;e.fill=false;e.alpha=.8f;editingTemplate.elements.add(e);editorView.selected=editingTemplate.elements.size()-1;editorView.invalidate();syncControls();});add.addView(addRect,new LinearLayout.LayoutParams(0,dp(52),1));body.addView(add);

        LinearLayout select=card();select.addView(text("Selected element controls",14,white,true));Button editText=button("EDIT TEXT / TOKENS",blue);editText.setOnClickListener(v->editSelectedText());select.addView(editText);
        Spinner font=new Spinner(this);font.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Sans","Serif","Monospace"}));font.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){boolean ready=false;public void onNothingSelected(android.widget.AdapterView<?> a){}public void onItemSelected(android.widget.AdapterView<?> a,View v,int pos,long id){if(!ready){ready=true;return;}OverlayProcessor.Element e=editorView==null?null:editorView.selectedElement();if(e!=null&&"text".equals(e.type)){e.font=pos==1?"serif":(pos==2?"monospace":"sans-serif");editorView.invalidate();}}});select.addView(font,new LinearLayout.LayoutParams(-1,dp(50)));
        CheckBox bold=new CheckBox(this);bold.setText("Bold text");bold.setTextColor(white);bold.setOnCheckedChangeListener((b,on)->{OverlayProcessor.Element e=editorView==null?null:editorView.selectedElement();if(e!=null&&"text".equals(e.type)){e.bold=on;editorView.invalidate();}});select.addView(bold);
        TextView ts=text("Text / element size",12,muted,true);select.addView(ts);SeekBar size=new SeekBar(this);size.setMax(100);size.setProgress(45);size.setOnSeekBarChangeListener(simpleSeek(v->{OverlayProcessor.Element e=editorView==null?null:editorView.selectedElement();if(e==null)return;if("text".equals(e.type))e.textSize=.018f+(v/100f)*.12f;else{float s=.06f+(v/100f)*.75f;e.w=s;e.h=s;}editorView.invalidate();}));select.addView(size);
        select.addView(text("Transparency",12,muted,true));SeekBar opacity=new SeekBar(this);opacity.setMax(100);opacity.setProgress(100);opacity.setOnSeekBarChangeListener(simpleSeek(v->{OverlayProcessor.Element e=editorView==null?null:editorView.selectedElement();if(e!=null){e.alpha=v/100f;editorView.invalidate();}}));select.addView(opacity);
        LinearLayout turn=new LinearLayout(this);Button left=button("↶ 15°",Color.rgb(70,80,90));left.setOnClickListener(v->{OverlayProcessor.Element e=editorView.selectedElement();if(e!=null){e.rotation-=15;editorView.invalidate();}});turn.addView(left,new LinearLayout.LayoutParams(0,dp(50),1));Button right=button("↷ 15°",Color.rgb(70,80,90));right.setOnClickListener(v->{OverlayProcessor.Element e=editorView.selectedElement();if(e!=null){e.rotation+=15;editorView.invalidate();}});turn.addView(right,new LinearLayout.LayoutParams(0,dp(50),1));Button del=button("DELETE",red);del.setOnClickListener(v->{if(editorView.selected>=0&&editorView.selected<editingTemplate.elements.size()){editingTemplate.elements.remove(editorView.selected);editorView.selected=-1;editorView.invalidate();}});turn.addView(del,new LinearLayout.LayoutParams(0,dp(50),1));select.addView(turn);body.addView(select);
        editorView.selectionChanged=()->{OverlayProcessor.Element e=editorView.selectedElement();if(e!=null){bold.setChecked(e.bold);opacity.setProgress((int)(e.alpha*100));size.setProgress("text".equals(e.type)?Math.max(0,Math.min(100,(int)((e.textSize-.018f)/.12f*100))):Math.max(0,Math.min(100,(int)((e.w-.06f)/.75f*100))));}};

        LinearLayout saveRow=new LinearLayout(this);Button duplicate=button("DUPLICATE",amber);duplicate.setOnClickListener(v->{OverlayProcessor.Template copy=editingTemplate.copy();OverlayProcessor.saveTemplate(this,copy);toast("Template duplicated");drawEditor(copy);});saveRow.addView(duplicate,new LinearLayout.LayoutParams(0,dp(54),1));Button save=button("SAVE TEMPLATE",green);save.setOnClickListener(v->{editingTemplate.name=name.getText().toString().trim().isEmpty()?"Custom Template":name.getText().toString().trim();editingTemplate.orientation=orient.getSelectedItemPosition()==1?"portrait":"landscape";OverlayProcessor.saveTemplate(this,editingTemplate);p.edit().putString("portrait".equals(editingTemplate.orientation)?OverlayProcessor.PREF_PORTRAIT_TEMPLATE:OverlayProcessor.PREF_LANDSCAPE_TEMPLATE,editingTemplate.id).apply();toast("Template saved");editingTemplate=null;drawMain();});saveRow.addView(save,new LinearLayout.LayoutParams(0,dp(54),1));body.addView(saveRow);
        Button deleteTemplate=button("DELETE TEMPLATE",red);deleteTemplate.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Delete template?").setMessage(editingTemplate.name).setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{OverlayProcessor.deleteTemplate(this,editingTemplate.id);editingTemplate=null;drawMain();}).show());body.addView(deleteTemplate);
    }

    private interface SeekAction{void run(int value);}private SeekBar.OnSeekBarChangeListener simpleSeek(SeekAction a){return new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int v,boolean from){if(from)a.run(v);}};}
    private void syncControls(){if(editorView!=null&&editorView.selectionChanged!=null)editorView.selectionChanged.run();}
    private void addText(){final EditText x=input("Text or token: {PLAYER_NAME} {NUMBER} {TEAM} {EVENT} {DATE} {PHOTOGRAPHER}","{PLAYER_NAME}");new AlertDialog.Builder(this).setTitle("Add text").setView(x).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{OverlayProcessor.Element e=new OverlayProcessor.Element();e.type="text";e.text=x.getText().toString();e.x=.08f;e.y=.20f;editingTemplate.elements.add(e);editorView.selected=editingTemplate.elements.size()-1;editorView.invalidate();syncControls();}).show();}
    private void editSelectedText(){OverlayProcessor.Element e=editorView==null?null:editorView.selectedElement();if(e==null||!"text".equals(e.type)){toast("Select a text element first");return;}EditText x=input("Text / tokens",e.text);new AlertDialog.Builder(this).setTitle("Edit text").setMessage("Tokens: {PLAYER_NAME}, {NUMBER}, {TEAM}, {EVENT}, {DATE}, {PHOTOGRAPHER}").setView(x).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{e.text=x.getText().toString();editorView.invalidate();}).show();}

    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(resultCode!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();if(requestCode==REQ_LOGO&&editingTemplate!=null){try{String path=OverlayProcessor.copyAssetIntoModule(this,u,"overlay.png");OverlayProcessor.Element e=new OverlayProcessor.Element();e.type="image";e.assetPath=path;e.x=.5f;e.y=.5f;e.w=.28f;e.h=.28f;editingTemplate.elements.add(e);editorView.selected=editingTemplate.elements.size()-1;editorView.invalidate();toast("Graphic added");}catch(Exception e){toast("Could not add graphic: "+e.getMessage());}}else if(requestCode==REQ_PREVIEW){previewSource=u;renderPreview();}}

    private void renderPreview(){if(previewSource==null)return;new Thread(()->{try{boolean portrait=isPortrait(previewSource);String id=p.getString(portrait?OverlayProcessor.PREF_PORTRAIT_TEMPLATE:OverlayProcessor.PREF_LANDSCAPE_TEMPLATE,"");Bitmap b=OverlayProcessor.preview(this,previewSource,id);runOnUiThread(()->previewImage.setImageBitmap(b));}catch(Exception e){runOnUiThread(()->toast("Preview failed: "+e.getMessage()));}}).start();}
    private boolean isPortrait(Uri u){try(android.database.Cursor c=getContentResolver().query(u,new String[]{MediaStore.Images.Media.WIDTH,MediaStore.Images.Media.HEIGHT},null,null,null)){return c!=null&&c.moveToFirst()&&c.getInt(1)>c.getInt(0);}catch(Exception e){return false;}}

    private void section(String s){TextView v=text(s.toUpperCase(Locale.US),12,muted,true);v.setPadding(dp(4),dp(16),dp(4),dp(6));body.addView(v);}
    private LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(12),dp(12),dp(12),dp(12));x.setBackground(round(panel,16,line));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(10));x.setLayoutParams(lp);return x;}
    private TextView text(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setPadding(dp(4),dp(5),dp(4),dp(5));if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
    private EditText input(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(muted);e.setTextColor(white);e.setText(value);e.setSingleLine(true);e.setPadding(dp(10),dp(6),dp(10),dp(6));return e;}
    private Button button(String s,int color){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(12);b.setAllCaps(false);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(color));return b;}
    private TextView statusRow(String k,String v,int color){TextView t=text(k+"\n"+v,13,color,true);t.setBackground(round(Color.rgb(11,17,23),12,line));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(58));lp.setMargins(0,0,0,dp(6));t.setLayoutParams(lp);return t;}
    private void styleSwitch(Switch s,String label,boolean on){s.setText(label);s.setTextColor(white);s.setChecked(on);s.setPadding(dp(6),dp(8),dp(6),dp(8));}
    private GradientDrawable round(int fill,int radius,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));g.setStroke(dp(1),stroke);return g;}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}

    /** Simple touch editor using normalized coordinates so templates scale to any photo resolution. */
    private final class EditorView extends View {
        final OverlayProcessor.Template template;int selected=-1;Runnable selectionChanged;Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);RectF canvasRect=new RectF();float lastX,lastY,startDistance,startAngle,startW,startH,startText,startRotation;boolean twoFinger=false;
        EditorView(Context c,OverlayProcessor.Template t){super(c);template=t;setBackgroundColor(Color.rgb(9,14,19));}
        OverlayProcessor.Element selectedElement(){return selected>=0&&selected<template.elements.size()?template.elements.get(selected):null;}
        @Override protected void onDraw(Canvas c){super.onDraw(c);float pad=dp(14);float availW=getWidth()-2*pad,availH=getHeight()-2*pad;float ratio="portrait".equals(template.orientation)?.72f:1.5f;float w=availW,h=w/ratio;if(h>availH){h=availH;w=h*ratio;}float l=(getWidth()-w)/2f,t=(getHeight()-h)/2f;canvasRect.set(l,t,l+w,t+h);paint.setStyle(Paint.Style.FILL);paint.setColor(Color.rgb(38,48,58));c.drawRect(canvasRect,paint);paint.setShader(new LinearGradient(l,t,l+w,t+h,Color.rgb(60,75,90),Color.rgb(18,24,30),Shader.TileMode.CLAMP));c.drawRect(canvasRect,paint);paint.setShader(null);paint.setTextAlign(Paint.Align.CENTER);paint.setTextSize(dp(16));paint.setColor(Color.argb(140,255,255,255));c.drawText("PHOTO",canvasRect.centerX(),canvasRect.centerY(),paint);
            for(int i=0;i<template.elements.size();i++){OverlayProcessor.Element e=template.elements.get(i);float x=l+e.x*w,y=t+e.y*h;c.save();c.rotate(e.rotation,x,y);paint.setAlpha((int)(255*e.alpha));if("text".equals(e.type)){paint.setStyle(Paint.Style.FILL);paint.setColor(e.color);paint.setTextSize(Math.max(dp(10),e.textSize*Math.min(w,h)));paint.setTypeface(Typeface.create(e.font,e.bold?Typeface.BOLD:Typeface.NORMAL));paint.setTextAlign("right".equals(e.align)?Paint.Align.RIGHT:("center".equals(e.align)?Paint.Align.CENTER:Paint.Align.LEFT));c.drawText(e.text==null?"Text":e.text,x,y,paint);}else if("image".equals(e.type)){paint.setStyle(Paint.Style.FILL);paint.setColor(Color.argb((int)(200*e.alpha),33,150,243));c.drawRect(x-e.w*w/2f,y-e.h*h/2f,x+e.w*w/2f,y+e.h*h/2f,paint);paint.setTextAlign(Paint.Align.CENTER);paint.setTextSize(dp(11));paint.setColor(Color.WHITE);c.drawText("LOGO / PNG",x,y,paint);}else{paint.setStyle(e.fill?Paint.Style.FILL:Paint.Style.STROKE);paint.setStrokeWidth(dp(3));paint.setColor(e.color);c.drawRect(x,y,x+e.w*w,y+e.h*h,paint);}if(i==selected){paint.setAlpha(255);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(2));paint.setColor(amber);RectF b=boundsFor(e,x,y,w,h);c.drawRect(b,paint);}c.restore();}paint.setAlpha(255);}
        private RectF boundsFor(OverlayProcessor.Element e,float x,float y,float w,float h){if("text".equals(e.type)){float tw=Math.max(dp(80),w*.32f),th=Math.max(dp(38),e.textSize*Math.min(w,h)*1.4f);if("right".equals(e.align))return new RectF(x-tw,y-th,x,y+dp(8));if("center".equals(e.align))return new RectF(x-tw/2,y-th,x+tw/2,y+dp(8));return new RectF(x,y-th,x+tw,y+dp(8));}if("image".equals(e.type))return new RectF(x-e.w*w/2,y-e.h*h/2,x+e.w*w/2,y+e.h*h/2);return new RectF(x,y,x+e.w*w,y+e.h*h);}
        private int hit(float px,float py){float w=canvasRect.width(),h=canvasRect.height();for(int i=template.elements.size()-1;i>=0;i--){OverlayProcessor.Element e=template.elements.get(i);float x=canvasRect.left+e.x*w,y=canvasRect.top+e.y*h;RectF b=boundsFor(e,x,y,w,h);b.inset(-dp(18),-dp(18));if(b.contains(px,py))return i;}return -1;}
        @Override public boolean onTouchEvent(android.view.MotionEvent ev){if(!canvasRect.contains(ev.getX(),ev.getY())&&ev.getActionMasked()==MotionEvent.ACTION_DOWN)return false;OverlayProcessor.Element e=selectedElement();switch(ev.getActionMasked()){
            case MotionEvent.ACTION_DOWN:selected=hit(ev.getX(),ev.getY());lastX=ev.getX();lastY=ev.getY();twoFinger=false;if(selectionChanged!=null)selectionChanged.run();invalidate();return true;
            case MotionEvent.ACTION_POINTER_DOWN:if(selectedElement()!=null&&ev.getPointerCount()>=2){e=selectedElement();twoFinger=true;startDistance=distance(ev);startAngle=angle(ev);startW=e.w;startH=e.h;startText=e.textSize;startRotation=e.rotation;}return true;
            case MotionEvent.ACTION_MOVE:e=selectedElement();if(e==null)return true;if(ev.getPointerCount()>=2&&twoFinger){float scale=startDistance<=0?1f:distance(ev)/startDistance;e.rotation=startRotation+(angle(ev)-startAngle);if("text".equals(e.type))e.textSize=clamp(startText*scale,.012f,.20f);else{e.w=clamp(startW*scale,.03f,1.5f);e.h=clamp(startH*scale,.03f,1.5f);}invalidate();return true;}float dx=(ev.getX()-lastX)/Math.max(1,canvasRect.width()),dy=(ev.getY()-lastY)/Math.max(1,canvasRect.height());e.x=clamp(e.x+dx,-.25f,1.25f);e.y=clamp(e.y+dy,-.25f,1.25f);lastX=ev.getX();lastY=ev.getY();invalidate();return true;
            case MotionEvent.ACTION_POINTER_UP:twoFinger=false;return true;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:twoFinger=false;return true;}return true;}
        float distance(MotionEvent e){float dx=e.getX(0)-e.getX(1),dy=e.getY(0)-e.getY(1);return (float)Math.sqrt(dx*dx+dy*dy);}float angle(MotionEvent e){return (float)Math.toDegrees(Math.atan2(e.getY(1)-e.getY(0),e.getX(1)-e.getX(0)));}float clamp(float v,float lo,float hi){return Math.max(lo,Math.min(hi,v));}
    }
}
