package com.nikonautoupload;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.io.File;
import java.util.*;

/** Full-screen direct-manipulation photo/card editor. */
public class TouchTemplateEditorActivity extends Activity {
    private static final int REQ_PHOTO=901,REQ_PNG=902,REQ_LOGO=903;
    private final int bg=Color.rgb(5,8,12),panel=Color.rgb(18,24,31),white=Color.rgb(245,247,250),muted=Color.rgb(160,170,181),blue=Color.rgb(33,150,243),green=Color.rgb(55,206,108),red=Color.rgb(239,83,80),amber=Color.rgb(255,193,7);
    private SharedPreferences p;
    private OverlayProcessor.Template template;
    private TouchCanvas canvas;
    private TextView title,status;
    private Button lockButton;
    private boolean photoEditorMode=false,explicitTemplate=false,grid=false;
    private final ArrayDeque<String> undo=new ArrayDeque<>(),redo=new ArrayDeque<>();

    @Override public void onCreate(Bundle b){
        super.onCreate(b);p=getSharedPreferences("settings",MODE_PRIVATE);photoEditorMode=getIntent().getBooleanExtra("photo_editor",false);
        String id=getIntent().getStringExtra("template_id");explicitTemplate=id!=null&&!id.isEmpty();template=explicitTemplate?OverlayProcessor.findTemplate(this,id):activeTemplate(false);
        if(template==null){template=new OverlayProcessor.Template();template.name=photoEditorMode?"Photo Editor Layout":"Touch Template";template.category="Custom";template.orientation=getIntent().getStringExtra("orientation");if(template.orientation==null)template.orientation="portrait";}
        draw();String photo=getIntent().getStringExtra("photo_uri");if(photo!=null&&!photo.isEmpty())canvas.loadPhoto(Uri.parse(photo),true);
    }

    private OverlayProcessor.Template activeTemplate(boolean portrait){
        String key=portrait?OverlayProcessor.PREF_PORTRAIT_TEMPLATE:OverlayProcessor.PREF_LANDSCAPE_TEMPLATE;String id=p.getString(key,"");OverlayProcessor.Template t=OverlayProcessor.findTemplate(this,id);if(t!=null)return t;
        ArrayList<OverlayProcessor.Template> all=OverlayProcessor.loadTemplates(this);for(OverlayProcessor.Template x:all)if((portrait?"portrait":"landscape").equals(x.orientation))return x;return null;
    }

    private void draw(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(8),dp(6),dp(8),dp(6));
        Button back=button("‹",Color.rgb(55,65,76));back.setTextSize(26);back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(50),dp(48)));
        title=text(photoEditorMode?"Photo Editor":template.name,18,white,true);top.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));
        lockButton=button(p.getBoolean("editor_layout_locked",false)?"LOCKED":"LOCK",p.getBoolean("editor_layout_locked",false)?green:Color.rgb(70,80,90));lockButton.setOnClickListener(v->toggleAutoLock());top.addView(lockButton,new LinearLayout.LayoutParams(dp(82),dp(46)));
        Button save=button("SAVE",red);save.setOnClickListener(v->saveTemplate(true));top.addView(save,new LinearLayout.LayoutParams(dp(72),dp(46)));root.addView(top);

        status=text("Tap photo, text, number, logo or frame directly • drag • pinch • twist • double-tap text",12,muted,false);status.setPadding(dp(12),dp(3),dp(12),dp(6));root.addView(status);
        canvas=new TouchCanvas(this);root.addView(canvas,new LinearLayout.LayoutParams(-1,0,1));

        HorizontalScrollView toolsScroll=new HorizontalScrollView(this);toolsScroll.setHorizontalScrollBarEnabled(false);LinearLayout tools=new LinearLayout(this);tools.setPadding(dp(5),dp(4),dp(5),dp(4));toolsScroll.addView(tools);root.addView(toolsScroll,new LinearLayout.LayoutParams(-1,dp(62)));
        addTool(tools,"PHOTO",blue,v->pick(REQ_PHOTO,"image/*"));addTool(tools,"FRAME",green,v->pick(REQ_PNG,"image/png"));addTool(tools,"TEXT",blue,v->addCustomText());addTool(tools,"NAME",blue,v->addToken("{PLAYER_NAME}",.5f,.82f,.07f));addTool(tools,"#",blue,v->addToken("{NUMBER}",.82f,.82f,.09f));addTool(tools,"POSITION",blue,v->addToken("{POSITION}",.5f,.92f,.045f));addTool(tools,"LOGO",green,v->pick(REQ_LOGO,"image/*"));addTool(tools,"SHAPE",Color.rgb(90,75,130),v->addShape());addTool(tools,"COLOR",Color.rgb(90,75,130),v->editColor());addTool(tools,"LAYERS",Color.rgb(70,80,90),v->showLayers());

        HorizontalScrollView actionsScroll=new HorizontalScrollView(this);actionsScroll.setHorizontalScrollBarEnabled(false);LinearLayout actions=new LinearLayout(this);actions.setPadding(dp(5),dp(3),dp(5),dp(5));actionsScroll.addView(actions);root.addView(actionsScroll,new LinearLayout.LayoutParams(-1,dp(58)));
        addAction(actions,"UNDO",v->undoAction());addAction(actions,"REDO",v->redoAction());addAction(actions,"FIT PHOTO",v->{checkpoint();template.photoX=.5f;template.photoY=.5f;template.photoScale=1f;template.photoRotation=0f;canvas.selectPhoto();});addAction(actions,"FIT VIEW",v->canvas.fitView());addAction(actions,"FRONT",v->moveLayer(1));addAction(actions,"BACK",v->moveLayer(-1));addAction(actions,"COPY",v->duplicateSelected());addAction(actions,"DELETE",v->deleteSelected());addAction(actions,"GRID",v->{grid=!grid;canvas.invalidate();});
        setContentView(root);
    }

    private void addTool(LinearLayout row,String label,int color,View.OnClickListener l){Button b=button(label,color);b.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(90),dp(50));lp.setMargins(dp(3),0,dp(3),0);row.addView(b,lp);}
    private void addAction(LinearLayout row,String label,View.OnClickListener l){Button b=button(label,Color.rgb(38,47,58));b.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(88),dp(46));lp.setMargins(dp(3),0,dp(3),0);row.addView(b,lp);}
    private void pick(int req,String type){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType(type).addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,req);}

    private void checkpoint(){try{undo.push(template.toJson().toString());while(undo.size()>30)undo.removeLast();redo.clear();}catch(Exception ignored){}}
    private void undoAction(){if(undo.isEmpty()){toast("Nothing to undo");return;}try{redo.push(template.toJson().toString());template=OverlayProcessor.Template.fromJson(new JSONObject(undo.pop()));canvas.selected=-1;canvas.invalidate();status.setText("Undo");}catch(Exception ignored){}}
    private void redoAction(){if(redo.isEmpty()){toast("Nothing to redo");return;}try{undo.push(template.toJson().toString());template=OverlayProcessor.Template.fromJson(new JSONObject(redo.pop()));canvas.selected=-1;canvas.invalidate();status.setText("Redo");}catch(Exception ignored){}}

    private void saveTemplate(boolean toast){OverlayProcessor.saveTemplate(this,template);String key="portrait".equals(template.orientation)?OverlayProcessor.PREF_PORTRAIT_TEMPLATE:OverlayProcessor.PREF_LANDSCAPE_TEMPLATE;p.edit().putString(key,template.id).apply();if(toast)toast("Layout saved");}
    private void toggleAutoLock(){
        if(p.getBoolean("editor_layout_locked",false)){p.edit().putBoolean("editor_layout_locked",false).putBoolean(OverlayProcessor.PREF_AUTO,false).apply();lockButton.setText("LOCK");lockButton.setBackground(rounded(Color.rgb(70,80,90),12));toast("Automatic editor layout unlocked");return;}
        final String[] choices={"Original only","Edited/card only","Both original + edited"};String cur=p.getString(OverlayProcessor.PREF_UPLOAD_CHOICE,OverlayProcessor.CHOICE_OVERLAY);int checked=OverlayProcessor.CHOICE_ORIGINAL.equals(cur)?0:(OverlayProcessor.CHOICE_BOTH.equals(cur)?2:1);
        new AlertDialog.Builder(this).setTitle("Lock this layout for new photos").setMessage("New camera/phone imports will keep the original untouched, then automatically use this saved layout. Choose what should enter the Flickr queue.").setSingleChoiceItems(choices,checked,null).setNegativeButton("Cancel",null).setPositiveButton("LOCK AUTO",(d,w)->{AlertDialog a=(AlertDialog)d;int n=a.getListView().getCheckedItemPosition();String q=n==0?OverlayProcessor.CHOICE_ORIGINAL:(n==2?OverlayProcessor.CHOICE_BOTH:OverlayProcessor.CHOICE_OVERLAY);saveTemplate(false);p.edit().putBoolean("editor_layout_locked",true).putBoolean(OverlayProcessor.PREF_AUTO,true).putString(OverlayProcessor.PREF_UPLOAD_CHOICE,q).apply();lockButton.setText("LOCKED");lockButton.setBackground(rounded(green,12));toast("Layout locked for automatic incoming photos");}).show();
    }

    private void addToken(String token,float x,float y,float size){checkpoint();OverlayProcessor.Element e=new OverlayProcessor.Element();e.type="text";e.text=token;e.x=x;e.y=y;e.textSize=size;e.align="center";e.bold=true;template.elements.add(e);canvas.select(template.elements.size()-1);}
    private void addCustomText(){EditText e=input("Text","Text");new AlertDialog.Builder(this).setTitle("Add text").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{checkpoint();OverlayProcessor.Element x=new OverlayProcessor.Element();x.type="text";x.text=e.getText().toString();x.x=.5f;x.y=.5f;x.textSize=.06f;x.align="center";template.elements.add(x);canvas.select(template.elements.size()-1);}).show();}
    private void addShape(){checkpoint();OverlayProcessor.Element e=new OverlayProcessor.Element();e.type="rect";e.x=.25f;e.y=.25f;e.w=.5f;e.h=.25f;e.fill=false;e.color=Color.WHITE;template.elements.add(e);canvas.select(template.elements.size()-1);}
    void editSelectedText(){OverlayProcessor.Element x=canvas.selectedElement();if(x==null||!"text".equals(x.type))return;EditText e=input("Text or token",x.text);new AlertDialog.Builder(this).setTitle("Edit text").setMessage("Tokens: {PLAYER_NAME}, {NUMBER}, {POSITION}, {TEAM}, {EVENT}, {DATE}, {PHOTOGRAPHER}").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{checkpoint();x.text=e.getText().toString();canvas.invalidate();}).show();}

    private void editColor(){OverlayProcessor.Element e=canvas.selectedElement();if(e==null){toast(canvas.selected==TouchCanvas.PHOTO?"Photo color tools are coming next":"Tap a layer first");return;}if("image".equals(e.type)){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);EditText hex=input("Tint #RRGGBB",String.format(Locale.US,"#%06X",0xFFFFFF&e.tintColor));box.addView(hex);SeekBar amount=new SeekBar(this);amount.setMax(100);amount.setProgress(Math.round(e.tint*100));box.addView(amount);new AlertDialog.Builder(this).setTitle("Recolor image layer").setMessage("0% keeps original colors. Increase tint to shift it toward a team color.").setView(box).setNegativeButton("Cancel",null).setNeutralButton("Clear",(d,w)->{checkpoint();e.tint=0;e.tintColor=Color.WHITE;canvas.invalidate();}).setPositiveButton("Apply",(d,w)->{try{checkpoint();e.tintColor=Color.parseColor(hex.getText().toString().trim());e.tint=amount.getProgress()/100f;canvas.invalidate();}catch(Exception ex){toast("Use a color like #CC2027");}}).show();return;}EditText hex=input("Color #RRGGBB",String.format(Locale.US,"#%06X",0xFFFFFF&e.color));new AlertDialog.Builder(this).setTitle("Layer color").setView(hex).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{try{checkpoint();e.color=Color.parseColor(hex.getText().toString().trim());canvas.invalidate();}catch(Exception ex){toast("Use a color like #FFFFFF");}}).show();}

    private void moveLayer(int direction){if(canvas.selected<0)return;int from=canvas.selected,to=Math.max(0,Math.min(template.elements.size()-1,from+direction));if(from==to)return;checkpoint();OverlayProcessor.Element e=template.elements.remove(from);template.elements.add(to,e);canvas.select(to);}
    private void duplicateSelected(){OverlayProcessor.Element e=canvas.selectedElement();if(e==null)return;checkpoint();OverlayProcessor.Element c=e.copy();c.id=UUID.randomUUID().toString();c.x+=.025f;c.y+=.025f;template.elements.add(c);canvas.select(template.elements.size()-1);}
    private void deleteSelected(){if(canvas.selected<0)return;checkpoint();template.elements.remove(canvas.selected);canvas.selected=-1;canvas.invalidate();status.setText("Layer deleted");}
    private void showLayers(){ArrayList<String> names=new ArrayList<>();names.add((canvas.selected==TouchCanvas.PHOTO?"✓ ":"")+"PHOTO");for(int i=0;i<template.elements.size();i++){OverlayProcessor.Element e=template.elements.get(i);String n="text".equals(e.type)?displayText(e.text):("image".equals(e.type)?"PNG / image":"Shape");names.add((i==canvas.selected?"✓ ":"")+n);}new AlertDialog.Builder(this).setTitle("Layers — bottom to top").setItems(names.toArray(new String[0]),(d,i)->{if(i==0)canvas.selectPhoto();else canvas.select(i-1);}).setNegativeButton("Close",null).show();}

    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();try{if(req==REQ_PHOTO){canvas.loadPhoto(u,false);return;}checkpoint();String path=OverlayProcessor.copyAssetIntoModule(this,u,req==REQ_PNG?"template.png":"logo.png");OverlayProcessor.Element e=new OverlayProcessor.Element();e.type="image";e.assetPath=path;e.x=.5f;e.y=.5f;e.w=req==REQ_PNG?1f:.25f;e.h=req==REQ_PNG?1f:.25f;e.alpha=1f;e.tint=0f;if(req==REQ_PNG)template.elements.add(0,e);else template.elements.add(e);canvas.select(req==REQ_PNG?0:template.elements.size()-1);}catch(Exception ex){toast("Could not add image: "+ex.getMessage());}}

    private String displayText(String s){String x=s==null?"":s;String player=p.getString("overlay_player","");if(player.isEmpty())player="PLAYER NAME";String number=p.getString("overlay_number","");if(number.isEmpty())number="00";String position=p.getString("overlay_position","");if(position.isEmpty())position="POSITION";String team=p.getString("overlay_team","");if(team.isEmpty())team="TEAM";String event=p.getString("overlay_event","");if(event.isEmpty())event="EVENT";return x.replace("{PLAYER_NAME}",player).replace("{NUMBER}",number).replace("{POSITION}",position).replace("{TEAM}",team).replace("{EVENT}",event).replace("{PHOTOGRAPHER}",p.getString("overlay_photographer","PHOTOGRAPHER")).replace("{DATE}","DATE");}

    private final class TouchCanvas extends View {
        static final int PHOTO=-2,NONE=-1;
        int selected=NONE;Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);RectF card=new RectF();Bitmap photo;Map<String,Bitmap> cache=new HashMap<>();float viewZoom=1f,viewPanX=0,viewPanY=0,lastX,lastY,startDistance,startAngle,startW,startH,startText,startRotation,startViewZoom,startPhotoScale,startPhotoRotation,startMidX,startMidY;boolean moved=false,pinching=false;long lastTap=0;
        TouchCanvas(Context c){super(c);setBackgroundColor(Color.rgb(9,12,17));}
        void select(int i){selected=i;invalidate();OverlayProcessor.Element e=selectedElement();status.setText(e==null?(i==PHOTO?"PHOTO selected • drag • pinch • rotate":"Tap something on the image"):("Selected: "+("text".equals(e.type)?displayText(e.text):("image".equals(e.type)?"PNG / graphic":"shape"))+" • drag • pinch • rotate"));}
        void selectPhoto(){if(photo==null){toast("Choose a photo first");return;}select(PHOTO);}
        OverlayProcessor.Element selectedElement(){return selected>=0&&selected<template.elements.size()?template.elements.get(selected):null;}
        void fitView(){viewZoom=1f;viewPanX=0;viewPanY=0;invalidate();}
        void loadPhoto(Uri u,boolean fromIntent){try{ImageDecoder.Source src=ImageDecoder.createSource(getContentResolver(),u);Bitmap b=ImageDecoder.decodeBitmap(src,(d,info,s)->{int w=info.getSize().getWidth(),h=info.getSize().getHeight();double sc=Math.min(1d,Math.sqrt(5000000d/Math.max(1d,(double)w*h)));if(sc<.999)d.setTargetSize(Math.max(1,(int)(w*sc)),Math.max(1,(int)(h*sc)));d.setAllocator(ImageDecoder.ALLOCATOR_SOFTWARE);});boolean portrait=b.getHeight()>b.getWidth();if(photoEditorMode&&!explicitTemplate&&!fromIntent){OverlayProcessor.Template active=activeTemplate(portrait);if(active!=null)template=active;else template.orientation=portrait?"portrait":"landscape";}if(photo!=null)photo.recycle();photo=b;template.orientation=portrait?"portrait":"landscape";select(PHOTO);status.setText("PHOTO selected • drag it under the frame • pinch to zoom • twist to rotate");invalidate();}catch(Exception e){toast("Could not open photo");}}
        private void cardRect(){float pad=dp(8),aw=getWidth()-pad*2,ah=getHeight()-pad*2,ratio="portrait".equals(template.orientation)?.70f:1.50f,w=aw,h=w/ratio;if(h>ah){h=ah;w=h*ratio;}float cx=getWidth()/2f+viewPanX,cy=getHeight()/2f+viewPanY;w*=viewZoom;h*=viewZoom;card.set(cx-w/2,cy-h/2,cx+w/2,cy+h/2);}
        @Override protected void onDraw(Canvas c){super.onDraw(c);cardRect();paint.setColor(Color.rgb(28,35,43));paint.setStyle(Paint.Style.FILL);c.drawRect(card,paint);c.save();c.clipRect(card);if(photo!=null)drawPhoto(c);else{paint.setColor(Color.rgb(42,52,62));c.drawRect(card,paint);paint.setTextAlign(Paint.Align.CENTER);paint.setTextSize(dp(18));paint.setColor(Color.LTGRAY);c.drawText("TAP PHOTO TO CHOOSE AN IMAGE",card.centerX(),card.centerY(),paint);}c.restore();float w=card.width(),h=card.height(),base=Math.min(w,h);
            for(int i=0;i<template.elements.size();i++){OverlayProcessor.Element e=template.elements.get(i);if(e==null||!e.visible)continue;float x=card.left+e.x*w,y=card.top+e.y*h;c.save();c.rotate(e.rotation,x,y);paint.setAlpha(Math.max(0,Math.min(255,(int)(255*e.alpha))));paint.setColorFilter(null);if("text".equals(e.type)){paint.setStyle(Paint.Style.FILL);paint.setColor(e.color);paint.setTextSize(Math.max(dp(10),e.textSize*base));paint.setTypeface(Typeface.create(e.font,e.bold?Typeface.BOLD:Typeface.NORMAL));paint.setTextAlign("right".equals(e.align)?Paint.Align.RIGHT:("center".equals(e.align)?Paint.Align.CENTER:Paint.Align.LEFT));String[] lines=displayText(e.text).split("\\n",-1);float line=paint.getTextSize()*1.08f;for(int k=0;k<lines.length;k++)c.drawText(lines[k],x,y+k*line,paint);}else if("image".equals(e.type)){Bitmap b=image(e.assetPath);if(b!=null){if(e.tint>0.001f)paint.setColorFilter(OverlayProcessor.tintFilter(e.tintColor,e.tint));RectF d=new RectF(x-e.w*w/2f,y-e.h*h/2f,x+e.w*w/2f,y+e.h*h/2f);c.drawBitmap(b,null,d,paint);paint.setColorFilter(null);}}else{paint.setColor(e.color);paint.setStyle(e.fill?Paint.Style.FILL:Paint.Style.STROKE);paint.setStrokeWidth(Math.max(dp(2),base*.005f));c.drawRect(x,y,x+e.w*w,y+e.h*h,paint);}if(i==selected)drawSelection(c,bounds(e,x,y,w,h));c.restore();}
            if(selected==PHOTO&&photo!=null){c.save();c.rotate(template.photoRotation,photoCx(),photoCy());drawSelection(c,photoRect());c.restore();}if(grid)drawGrid(c);paint.setAlpha(255);paint.setColorFilter(null);}
        private void drawPhoto(Canvas c){RectF d=photoRect();c.save();c.rotate(template.photoRotation,photoCx(),photoCy());c.drawBitmap(photo,null,d,paint);c.restore();}
        private float photoCx(){return card.left+template.photoX*card.width();}private float photoCy(){return card.top+template.photoY*card.height();}
        private RectF photoRect(){if(photo==null)return new RectF(card);float base=Math.max(card.width()/photo.getWidth(),card.height()/photo.getHeight());float w=photo.getWidth()*base*template.photoScale,h=photo.getHeight()*base*template.photoScale,cx=photoCx(),cy=photoCy();return new RectF(cx-w/2,cy-h/2,cx+w/2,cy+h/2);}
        private void drawSelection(Canvas c,RectF b){paint.setAlpha(255);paint.setColor(amber);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(2));c.drawRect(b,paint);float r=dp(5);paint.setStyle(Paint.Style.FILL);c.drawCircle(b.left,b.top,r,paint);c.drawCircle(b.right,b.top,r,paint);c.drawCircle(b.left,b.bottom,r,paint);c.drawCircle(b.right,b.bottom,r,paint);}
        private void drawGrid(Canvas c){paint.setColor(Color.argb(95,255,255,255));paint.setStrokeWidth(dp(1));float sx=card.width()/3f,sy=card.height()/3f;for(int i=1;i<3;i++){c.drawLine(card.left+sx*i,card.top,card.left+sx*i,card.bottom,paint);c.drawLine(card.left,card.top+sy*i,card.right,card.top+sy*i,paint);}}
        private Bitmap image(String path){if(path==null||path.isEmpty())return null;if(cache.containsKey(path))return cache.get(path);File f=new File(path);Bitmap b=f.exists()?BitmapFactory.decodeFile(path):null;if(b!=null)cache.put(path,b);return b;}
        private RectF bounds(OverlayProcessor.Element e,float x,float y,float w,float h){if("text".equals(e.type)){paint.setTextSize(Math.max(dp(10),e.textSize*Math.min(w,h)));float tw=0;for(String line:displayText(e.text).split("\\n",-1))tw=Math.max(tw,paint.measureText(line));float th=paint.getTextSize()*1.25f;if("right".equals(e.align))return new RectF(x-tw,y-th,x,y+dp(8));if("center".equals(e.align))return new RectF(x-tw/2,y-th,x+tw/2,y+dp(8));return new RectF(x,y-th,x+tw,y+dp(8));}if("image".equals(e.type))return new RectF(x-e.w*w/2,y-e.h*h/2,x+e.w*w/2,y+e.h*h/2);return new RectF(x,y,x+e.w*w,y+e.h*h);}
        private int hit(float px,float py){float w=card.width(),h=card.height();for(int i=template.elements.size()-1;i>=0;i--){OverlayProcessor.Element e=template.elements.get(i);if(e==null||!e.visible)continue;float x=card.left+e.x*w,y=card.top+e.y*h;RectF b=bounds(e,x,y,w,h);b.inset(-dp(18),-dp(18));if(b.contains(px,py))return i;}return NONE;}
        @Override public boolean onTouchEvent(MotionEvent ev){cardRect();switch(ev.getActionMasked()){
            case MotionEvent.ACTION_DOWN:{int h=hit(ev.getX(),ev.getY());if(h==NONE&&photo!=null&&card.contains(ev.getX(),ev.getY()))h=PHOTO;selected=h;lastX=ev.getX();lastY=ev.getY();moved=false;pinching=false;if(selected>=0||selected==PHOTO)checkpoint();invalidate();status.setText(selected==PHOTO?"PHOTO selected • drag • pinch • rotate":(selected>=0?"Layer selected • drag • pinch • rotate":"Pinch outside the card to zoom the workspace"));return true;}
            case MotionEvent.ACTION_POINTER_DOWN:{if(ev.getPointerCount()>=2){pinching=true;startDistance=distance(ev);startAngle=angle(ev);startMidX=(ev.getX(0)+ev.getX(1))/2f;startMidY=(ev.getY(0)+ev.getY(1))/2f;if(selected==PHOTO){startPhotoScale=template.photoScale;startPhotoRotation=template.photoRotation;}else{OverlayProcessor.Element e=selectedElement();if(e!=null){startW=e.w;startH=e.h;startText=e.textSize;startRotation=e.rotation;}else startViewZoom=viewZoom;}}return true;}
            case MotionEvent.ACTION_MOVE:{moved=true;if(ev.getPointerCount()>=2&&pinching){float scale=startDistance<=0?1:distance(ev)/startDistance;if(selected==PHOTO){template.photoScale=clamp(startPhotoScale*scale,.15f,5f);template.photoRotation=startPhotoRotation+(angle(ev)-startAngle);invalidate();return true;}OverlayProcessor.Element e=selectedElement();if(e!=null){e.rotation=startRotation+(angle(ev)-startAngle);if("text".equals(e.type))e.textSize=clamp(startText*scale,.01f,.35f);else{e.w=clamp(startW*scale,.02f,3f);e.h=clamp(startH*scale,.02f,3f);}invalidate();return true;}viewZoom=clamp(startViewZoom*scale,.55f,5f);invalidate();return true;}float dx=ev.getX()-lastX,dy=ev.getY()-lastY;if(selected==PHOTO){template.photoX=clamp(template.photoX+dx/Math.max(1,card.width()),-1f,2f);template.photoY=clamp(template.photoY+dy/Math.max(1,card.height()),-1f,2f);invalidate();}else{OverlayProcessor.Element e=selectedElement();if(e!=null){e.x=clamp(e.x+dx/Math.max(1,card.width()),-1f,2f);e.y=clamp(e.y+dy/Math.max(1,card.height()),-1f,2f);invalidate();}else if(viewZoom>1f){viewPanX+=dx;viewPanY+=dy;invalidate();}}lastX=ev.getX();lastY=ev.getY();return true;}
            case MotionEvent.ACTION_POINTER_UP:pinching=false;return true;
            case MotionEvent.ACTION_UP:{long now=System.currentTimeMillis();if(!moved&&selected>=0){if(now-lastTap<360){OverlayProcessor.Element e=selectedElement();if(e!=null&&"text".equals(e.type))editSelectedText();lastTap=0;}else lastTap=now;}return true;}
        }return true;}
        private float distance(MotionEvent e){float dx=e.getX(0)-e.getX(1),dy=e.getY(0)-e.getY(1);return (float)Math.sqrt(dx*dx+dy*dy);}private float angle(MotionEvent e){return (float)Math.toDegrees(Math.atan2(e.getY(1)-e.getY(0),e.getX(1)-e.getX(0)));}
    }

    private float clamp(float v,float lo,float hi){return Math.max(lo,Math.min(hi,v));}
    private Button button(String s,int color){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(12);b.setAllCaps(false);b.setBackground(rounded(color,12));return b;}
    private GradientDrawable rounded(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private TextView text(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setPadding(dp(5),dp(5),dp(5),dp(5));if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
    private EditText input(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextColor(white);e.setHintTextColor(muted);e.setSingleLine(false);e.setPadding(dp(14),dp(10),dp(14),dp(10));return e;}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}